# .github/workflows/azure-resource-cleanup.yml
name: Clean-up Azure Resources

on:
    workflow_dispatch: # allows to run manually    
    schedule: 
        - cron: '0 0 * * *' # every day at midnight

permissions:
  id-token: write
  contents: read

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          echo "::set-output name=matrix::$input"
        env:
          input: ${{ vars.AZURE_SUBSCRIPTION_IDS }}
  azure-resource-cleanup-matrix:
    needs: setup-matrix
    strategy:
        matrix: 
          subscription_id: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Azure Login on subscription '${{ matrix.subscription_id }}'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ matrix.subscription_id }}
        enable-AzPSSession: true
    - name: Execute script for subscription '${{ matrix.subscription_id }}'
      uses: azure/powershell@v2
      with:
        inlineScript: ./Remove-AzResources.ps1 -SubscriptionId ${{ matrix.subscription_id }}
        azPSVersion: latest