# .github/workflows/azure-cleanup.yml
name: Clean-up Azure Resources

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  prepare-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true
    # - name: Create Resource Group
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #     azPSVersion: latest